version: "3"
services:
  api-server:
    image: api-server-prod
    restart: unless-stopped

    env_file:
      - .env
    ports:
      - "9000:9000"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
